/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as TokenImport } from "./routes/token.$tokenAddress";

// Create/Update Routes
const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const TokenRoute = TokenImport.update({
  id: "/token/$tokenAddress",
  path: "/token/$tokenAddress",
  getParentRoute: () => rootRoute,
} as any);


// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/token/$tokenAddress": {
      id: "/token/$tokenAddress";
      path: "/token/$tokenAddress";
      fullPath: "/token/$tokenAddress";
      preLoaderRoute: typeof TokenImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/token/$tokenAddress": typeof TokenRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/token/$tokenAddress": typeof TokenRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/token/$tokenAddress": typeof TokenRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/token/$tokenAddress";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/token/$tokenAddress";
  id: "__root__" | "/" | "/token/$tokenAddress";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  TokenRoute: typeof TokenRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokenRoute: TokenRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings",
        "/test",
        "/feed/$feedId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/feed/$feedId": {
      "filePath": "feed.$feedId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */